version: '3'
services:
    
    # Copy of database on 2018.09.04        
    mysqldb:
        image: rgru/web-db:5.6-with-data
        container_name: mysql-com
        network_mode: bridge
        ports:
            - "3305:3306"
        restart: always
    
    # to use in containers
    redis:
        image: redis
        container_name: redis-com
        network_mode: bridge
        ports:
            - "6399:6379"
        restart: always




    # To control database
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin-com
        network_mode: bridge
        ports:
            - "8005:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql-com
        restart: always
        depends_on:
            - mysqldb
        links:
            - mysqldb
